# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: Ruby

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['2.6', '2.7', '3.0']

    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
    # To automatically get bug fixes and new Ruby versions for ruby/setup-ruby,
    # change this to (see https://github.com/ruby/setup-ruby#versioning):
    # uses: ruby/setup-ruby@v1
      uses: ruby/setup-ruby@55283cc23133118229fd3f97f9336ee23a179fcf # v1.146.0
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: Run tests
      run: bundle exec rakecurl -X POST https://api.cash.app/customer-request/v1/requests \
     -H "Accept: Accept" \
     -H "User-Agent: User-Agent" \
     -H "Content-Type: application/json"
{
  "request": {
    "id": "GRR_1hrxhz136krcq6ezdte2ha5q",
    "status": "PENDING",
    "actions": [
      {
        "amount": 2500,
        "currency": "USD",
        "scope_id": "MMI_4vxs5egfk7hmta3qx2h6rp91x",
        "type": "ONE_TIME_PAYMENT"
      }
    ],
    "redirect_url": "https://example.com",
    "created_at": "2022-01-01T12:09:00Z",
    "updated_at": "2022-01-01T12:10:00Z",
    "expires_at": "2033-01-01T12:20:00Z",
    "origin": {
      "type": "DIRECT",
      "id": "string"
    },
    "channel": "ONLINE",
    "auth_flow_triggers": {
      "qr_code_image_url": "https://api.cash.app/qr/f/GRANTLY_MANAGED_GRANT%3Frequest_id=GRR_1hrxhz136krcq6ezdte2ha5q-k21srg&method=qr?rounded=0&format=png",
      "qr_code_svg_url": "https://api.cash.app/qr/f/GRANTLY_MANAGED_GRANT%3Frequest_id=GRR_1hrxhz136krcq6ezdte2ha5q-k21srg&method=qr?rounded=0&format=svg",
      "mobile_url": "https://cash.app/f/GRANTLY_MANAGED_GRANT%3Frequest_id=GRR_1hrxhz136krcq6ezdte2ha5q-k21srg&method=mobile_url",
      "refreshes_at": "2019-08-24T14:15:22Z",
      "desktop_url": "https://pay.cash.app?customerRequestId=GRR_1hrxhz136krcq6ezdte2ha5q"
    },
    "reference_id": "external-id",
    "requester_profile": {
      "name": "The Sill",
      "logo_url": "https://picsum.photos/200"
    },
    "metadata": {},
    "customer_metadata": {}
  }
}